// ── SHARED DATA ───────────────────────────────────────────────────────────────
const DEPARTURE  = new Date('2025-05-30T22:55:00');
const TRIP_START = new Date('2025-06-01T10:00:00');
const TRIP_END   = new Date('2025-06-25T16:30:00');

const STOPS = [
  { id:'bangkok',  name:'Bangkok',          flag:'🇹🇭', color:'#a78bfa', start:'2025-06-01', end:'2025-06-05' },
  { id:'chiangmai',name:'Chiang Mai',       flag:'🌿',  color:'#4ade80', start:'2025-06-05', end:'2025-06-08' },
  { id:'hanoi',    name:'Hanoi + Ha Giang', flag:'🇻🇳', color:'#60a5fa', start:'2025-06-08', end:'2025-06-15' },
  { id:'phuket',   name:'Phuket',           flag:'🏖️', color:'#e879f9', start:'2025-06-15', end:'2025-06-20' },
  { id:'bali',     name:'Bali',             flag:'🌴',  color:'#34d399', start:'2025-06-20', end:'2025-06-25' },
];

const PHOTOS = {
  1:'photo-1563492065599-3520f775eeed',2:'photo-1508009603885-50cf7c579365',
  3:'photo-1559628129-334f1e16f76b',  4:'photo-1529347788236-d06e2286c5b3',
  5:'photo-1583417319070-4a69db38a482',6:'photo-1551969014-7fafd76ebc25',
  7:'photo-1570197788417-0e82375c9371',8:'photo-1555993539-1732b0258235',
  9:'photo-1528360983277-13d401cdc186',10:'photo-1559493774-e5f4aa61f254',
  11:'photo-1506905489-1a876975a4a8', 12:'photo-1587826080692-e23dcc42e0f6',
  13:'photo-1590012314607-cda9d9b699ae',14:'photo-1555993539-1732b0258235',
  15:'photo-1507525428034-b723cf961d3e',16:'photo-1519451241324-20b4ea2c4220',
  17:'photo-1552465011-b4e21bf6e79a', 18:'photo-1558618666-fcd25c85cd64',
  19:'photo-1559601374-e34e72478fd2', 20:'photo-1602002418153-eeb6e54ef3b5',
  21:'photo-1555278987-b82d9bd4f461', 22:'photo-1573797952132-53b2b0e20e36',
  23:'photo-1571019613576-3b7847c89e43',24:'photo-1573797985-4c22c6249e56',
  25:'photo-1567521464027-f127ff144326',
};

function photoUrl(day,w=900){
  const id=PHOTOS[day]; if(!id) return null;
  return `https://images.unsplash.com/${id}?w=${w}&q=75&auto=format&fit=crop`;
}

function load(k,d){try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(e){return d}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}

const ITINERARY = [
  {day:1,date:'Jun 1',stop:'bangkok',title:'Arrival Day',
   acts:['Land 10am. Airport Rail Link to Phaya Thai ($2), Grab to Airbnb (~$4)','Check in, rest, recover from 30hr travel','Street food wander, get your bearings','Light intro to Khao San Road — don\'t overdo night one'],
   note:'Pre-drink at 7-Eleven before Khao San. Saves real money and is a Bangkok tradition.'},
  {day:2,date:'Jun 2',stop:'bangkok',title:'Grand Palace + Muay Thai',
   acts:['Grand Palace ($16pp) + Wat Pho ($4pp) — go early to beat the heat','Pratunam + Platinum Fashion Mall — cheap clothes, great quality, AC','Lumpinee Muay Thai Stadium (6:30pm, ~$40pp) — world-class professional fights','Khao San Road after — properly warmed up now'],
   note:'Dress code for Grand Palace: long pants and covered shoulders. Rentals available at the gate.'},
  {day:3,date:'Jun 3',stop:'bangkok',title:'Chatuchak + Jodd Fairs',
   acts:['BTS to Mo Chit → Chatuchak Weekend Market (free — Sat/Sun only)','Largest outdoor market in the world: clothes, street food, antiques','Afternoon: rest, pool, recharge','Jodd Fairs Night Market evening (free) — modern outdoor market, great vibes','Khao San Road after'],
   note:'Chatuchak is Saturday and Sunday only. Verify the date before locking this in as Day 3.'},
  {day:4,date:'Jun 4',stop:'bangkok',title:'Canal Tour + Chill Day',
   acts:['Canal (khlong) boat tour of historic Bangkok (~$18pp)','Chill afternoon: shopping, pool, street food','Optional: Icon Siam luxury mall for AC and incredible food court','Final Khao San Road night in Bangkok'],
   note:null},
  {day:5,date:'Jun 5',stop:'chiangmai',title:'Bangkok → Chiang Mai',
   acts:['Early Grab to Don Mueang Airport (DMK) — NOT Suvarnabhumi BKK','Fly to Chiang Mai, arrive ~10am–noon','Old City temple walk: Wat Chedi Luang + Wat Phra Singh (free, stunning)','Saturday Walking Street (Wua Lai Rd) or Sunday Walking Street (Tha Pae Gate)','Zoe in Yellow nightlife strip — Chiang Mai\'s backpacker hub'],
   note:'DMK = Don Mueang. Different airport from BKK Suvarnabhumi. Leave early.'},
  {day:6,date:'Jun 6',stop:'chiangmai',title:'Elephant Nature Park',
   acts:['Elephant Nature Park half-day ($70pp) — ethical sanctuary, no riding','Book through Mad Monkey hostel desk the previous evening. Pickup 7:30am.','Bathe and feed elephants in the river — genuinely extraordinary','Sunday Walking Street if the date falls right','Warm Up Café for live music and nightlife'],
   note:'Book Elephant Nature Park on Day 5 evening — it fills up. Ask the hostel desk on arrival.'},
  {day:7,date:'Jun 7',stop:'chiangmai',title:'Doi Suthep + Muay Thai',
   acts:['Doi Suthep temple + Sticky Waterfall (Bua Tong) day trip (~$30pp)','Sticky Waterfall: calcified waterfall you walk straight up barefoot — surreal','Nimman Road cafés and artisan shopping — best neighborhood in Chiang Mai','Muay Thai at Thapae Boxing Stadium ($25pp, 6:30pm)','Final Chiang Mai night'],
   note:null},
  {day:8,date:'Jun 8',stop:'hanoi',title:'Chiang Mai → Hanoi',
   acts:['Check out, Grab to CNX airport','Fly to Hanoi Noi Bai, arrive ~noon — tour covers check-in','Hoan Kiem Lake walk + Ngoc Son Temple (free, central)','Ta Hien Beer Street — Bia Hoi corner, 25 cent draft beers','Early night — night bus to Ha Giang departs tomorrow evening'],
   note:'Tour covers tonight\'s accommodation. Eat well, sleep early — big days ahead.'},
  {day:9,date:'Jun 9',stop:'hanoi',title:'Hanoi + Night Bus to Ha Giang',
   acts:['Ho Chi Minh Mausoleum + Temple of Literature ($8pp) — morning','Train Street + Old Quarter wander, street food lunch','Pack for the loop this afternoon, rest','8–9pm: Sleeper bus from My Dinh bus station to Ha Giang (~4.5hrs)','Arrive Ha Giang ~1am'],
   note:'My Dinh bus station — not Hanoi main station. Confirm pickup with your tour operator.'},
  {day:10,date:'Jun 10',stop:'hanoi',title:'Ha Giang Loop — Day 1',
   acts:['7:30am breakfast, meet your Easy Rider guide','Quan Ba Heaven Gate: panoramic view over the twin Fairy Bosom hills','Yen Minh for lunch','Dong Van Karst Plateau UNESCO Geopark — dramatic ancient limestone','Homestay night 1 in Dong Van: traditional dinner + corn rice wine (happy water)'],
   note:'Happy water = corn rice wine brewed by H\'Mong families. You drink it. That\'s the deal.'},
  {day:11,date:'Jun 11',stop:'hanoi',title:'Ha Giang Loop — Day 2',
   acts:['Ma Pi Leng Pass — crown jewel of the loop, one of Vietnam\'s great roads','Vertiginous road carved above the Nho Que River gorge','Meo Vac town for lunch','H\'Mong minority villages — traditional mountain life','Homestay night 2'],
   note:'Ma Pi Leng Pass: put your phone away. Actually look at it. You are there.'},
  {day:12,date:'Jun 12',stop:'hanoi',title:'Ha Giang Loop — Day 3',
   acts:['Lo Lo Chai village — traditional H\'Mong village, right on the Chinese border','Lung Cu Flag Tower: northernmost point of Vietnam on the Chinese border','Final dramatic mountain passes heading west','Homestay night 3','Tip your guide tonight: $15–20pp — they\'ve earned every dollar'],
   note:'Tip the guide in dong on Day 12 evening, before the last day. Cash only.'},
  {day:13,date:'Jun 13',stop:'hanoi',title:'Ha Giang Loop — Day 4',
   acts:['Scenic return to Ha Giang City, arriving ~3pm','Dinner in Ha Giang City — last meal on the loop','7–9pm: Sleeper bus back to Hanoi','Arrive Hanoi ~1–2am'],
   note:'Noi Bai guesthouse must be booked before this day. Do not wing it at 2am.'},
  {day:14,date:'Jun 14',stop:'hanoi',title:'Hanoi Free Day',
   acts:['Arrive ~2am → airport guesthouse near Noi Bai. Sleep.','Late morning: shower, eat, recover','Old Quarter + Dong Xuan Market for local shopping','Street food tour: bun cha, pho, banh mi, egg coffee','Final Bia Hoi night at Ta Hien corner','Fly to Phuket tomorrow'],
   note:'Target HAN→HKT flight 9am–1pm to give buffer after the 2am bus return. Don\'t book 7am.'},
  {day:15,date:'Jun 15',stop:'phuket',title:'Arrive Phuket',
   acts:['Fly from Hanoi, land at HKT Phuket','Check into Lub d Phuket Patong — great location, $18/night','Book Phi Phi Islands tour at hostel desk immediately — fills up fast','Explore Patong: loud, chaotic, bright, perfect','First night on Bangla Road — light intro, 4 nights ahead'],
   note:'Book Phi Phi speedboat tour at the desk today. Don\'t wait until tomorrow morning.'},
  {day:16,date:'Jun 16',stop:'phuket',title:'Phi Phi Islands',
   acts:['Full-day speedboat to Phi Phi Islands ($60pp) — departs Patong pier ~8:30am','Maya Bay (The Beach), Monkey Beach, Viking Cave, snorkeling, included lunch','Returns ~5pm. Grab to Promthep Cape for sunset — it\'s on the way back.','Bangla Road night 2'],
   note:'Promthep Cape: tell the driver after Phi Phi — south of Patong, 20-min detour, worth it.'},
  {day:17,date:'Jun 17',stop:'phuket',title:'Phang Nga Bay + Surf',
   acts:['Phang Nga Bay + James Bond Island half-day sea kayak ($45pp, morning)','Limestone karst islands, sea caves, floating village — incredible scenery','Back by 1pm. Lunch, rest.','Kata Beach surf lesson ($25pp) — better beginner waves than Patong','Bangla Road night 3'],
   note:'Kata Beach for surf. Patong Beach for swimming and the main scene.'},
  {day:18,date:'Jun 18',stop:'phuket',title:'ATV + Shopping Day',
   acts:['ATV jungle tour or full-island scooter day (~$40pp)','Patong Beach afternoon — swim, sunbathe, recover','Bang La Night Market + Thai souvenir shopping','Bangla Road night 4 — Tiger Disco, Illuzion, rooftop bars'],
   note:null},
  {day:19,date:'Jun 19',stop:'phuket',title:'Chill Beach Day',
   acts:['Chill beach day at Patong — swim, read, sunbathe','Promthep Cape sunset if not done yet (always worth it)','Final Bangla Road night in Phuket — make it count','Pack tonight for Bali tomorrow'],
   note:'Last night in Thailand.'},
  {day:20,date:'Jun 20',stop:'bali',title:'Phuket → Bali',
   acts:['Check out, Grab to HKT airport (45 min from Patong)','Fly to Bali Ngurah Rai (DPS)','Visa on Arrival: $35 USD cash, separate from wallet, 30–45 min queue','Buy Indonesia SIM at airport','Grab to Canggu (~45 min). Check in The Farm Hostel.','Rent scooter (~$7/day — essential in Bali). Canggu intro: Old Man\'s, La Laguna.'],
   note:'$35 USD CASH for Visa on Arrival. Exact amount. In a separate envelope. Ready before you land.'},
  {day:21,date:'Jun 21',stop:'bali',title:'Canggu + FINNS Beach Club',
   acts:['Chill Canggu morning — explore by scooter, find the rice paddy lanes','Check out the surf breaks at Batu Bolong and Echo Beach','FINNS Beach Club afternoon/evening — book a sunbed in advance for sunset','Infinity pool, cocktails, live DJ sets — best sunset in Canggu','Canggu bar strip after: Old Man\'s, La Laguna, Pretty Poison'],
   note:'Book FINNS sunbed online in advance. Walk-in at sunset is hit or miss.'},
  {day:22,date:'Jun 22',stop:'bali',title:'Mount Batur Sunrise Trek',
   acts:['1:30–2am: Guide picks up from The Farm. SET MULTIPLE ALARMS.','Trek up active volcano in darkness (~2 hours)','Summit at sunrise ~5:30–6:30am — views across all of Bali','Cook eggs in volcanic steam vents at the top ($40pp guided)','Back at The Farm by 10am. Sleep. Rest of the day is yours.','Canggu bars that evening — you\'ve earned it'],
   note:'The 2am pickup is not negotiable. Sleep in your trekking clothes if needed.'},
  {day:23,date:'Jun 23',stop:'bali',title:'Gili Trawangan Day Trip',
   acts:['Scooter east to Padang Bai harbor (1 hour)','Fast boat to Gili Trawangan ($30 each way, 1.5hrs)','Car-free island: snorkel with sea turtles, white sand, beach bars','Return boat ~5–6pm, back in Canggu by ~8–9pm','Canggu bar scene after'],
   note:'Book fast boat tickets in advance — June can sell out.'},
  {day:24,date:'Jun 24',stop:'bali',title:'Ubud + Final Night',
   acts:['Morning scooter to Tegalalang Rice Terraces ($3pp, 30 min)','Ubud Monkey Forest ($3pp — keep ALL valuables in bag, monkeys steal everything)','Ubud market: best gift shopping in Bali — batik, woodcarving, jewelry','Back to Canggu. Surf lesson at Batu Bolong ($25pp — walkable from hostel).','Final dinner — treat yourselves to something proper','Last night on the Canggu strip. Pack everything tonight.'],
   note:'Pack tonight. Flight is 4:30pm tomorrow and you leave hostel at 1pm.'},
  {day:25,date:'Jun 25',stop:'bali',title:'Fly Home',
   acts:['Check out The Farm by 11am','Last Canggu coffee and nasi goreng','1pm Grab to Ngurah Rai Airport DPS (45 min)','Arrive by 2pm for 4:30pm international departure','DPS → DFW. 26 nights. 5 stops. Done. Legend status unlocked.'],
   note:null},
];

const BUDGET_STOPS = [
  {id:'bangkok',name:'Bangkok',flag:'🇹🇭',color:'#a78bfa',planned:530,
   cats:[{key:'accommodation',label:'Accommodation',e:'🏨',p:105},{key:'food',label:'Food',e:'🍜',p:95},{key:'nightlife',label:'Nightlife',e:'🍻',p:160},{key:'activities',label:'Activities',e:'🎟️',p:38},{key:'shopping',label:'Shopping',e:'🛍️',p:90},{key:'transport',label:'Transport / SIM',e:'🚗',p:42}]},
  {id:'chiangmai',name:'Chiang Mai',flag:'🌿',color:'#4ade80',planned:455,
   cats:[{key:'accommodation',label:'Accommodation',e:'🏨',p:41},{key:'food',label:'Food',e:'🍜',p:85},{key:'nightlife',label:'Nightlife',e:'🍻',p:70},{key:'activities',label:'Activities',e:'🐘',p:125},{key:'shopping',label:'Shopping',e:'🛍️',p:100},{key:'transport',label:'Transport',e:'🚗',p:34}]},
  {id:'hanoi',name:'Hanoi + Ha Giang',flag:'🇻🇳',color:'#60a5fa',planned:630,
   cats:[{key:'tour',label:'Tour Package',e:'🏍️',p:400},{key:'accommodation',label:'Airport Guesthouse',e:'🏨',p:15},{key:'food',label:'Hanoi Food',e:'🍜',p:40},{key:'nightlife',label:'Nightlife',e:'🍺',p:25},{key:'shopping',label:'Shopping',e:'🛍️',p:40},{key:'extras',label:'Ha Giang Extras',e:'⛰️',p:80},{key:'tip',label:'Guide Tip',e:'💰',p:20},{key:'transport',label:'SIM + Grab + misc',e:'📱',p:10}]},
  {id:'phuket',name:'Phuket',flag:'🏖️',color:'#e879f9',planned:810,
   cats:[{key:'accommodation',label:'Accommodation',e:'🏨',p:90},{key:'food',label:'Food',e:'🍜',p:140},{key:'nightlife',label:'Nightlife',e:'🍻',p:220},{key:'activities',label:'Activities',e:'⛵',p:170},{key:'shopping',label:'Shopping',e:'🛍️',p:60},{key:'transport',label:'Transport',e:'🚗',p:35},{key:'extra',label:'Beach Club',e:'🏝️',p:95}]},
  {id:'bali',name:'Bali',flag:'🌴',color:'#34d399',planned:773,
   cats:[{key:'visa',label:'Visa on Arrival',e:'🛂',p:35},{key:'accommodation',label:'Accommodation',e:'🏨',p:65},{key:'food',label:'Food',e:'🍛',p:120},{key:'nightlife',label:'Nightlife',e:'🍹',p:190},{key:'activities',label:'Activities',e:'🌋',p:190},{key:'shopping',label:'Shopping',e:'🛍️',p:100},{key:'transport',label:'Scooter + SIM + GoJek',e:'🛵',p:73}]},
];

const CHECKLIST_GROUPS = [
  {title:'Book Immediately — Flights',items:[
    {id:'cl1',text:'Book HAN → HKT (Jun 15) — Thai AirAsia or VietJet — ~$130pp'},
    {id:'cl2',text:'Book HKT → DPS (Jun 20) — Indonesia AirAsia direct — ~$105pp'},
  ]},
  {title:'Already Booked — Confirm & File',items:[
    {id:'cl3',text:'DFW → BKK (May 30, 10:55pm) — $942pp ✓'},
    {id:'cl4',text:'DPS → DFW (Jun 25, 4:30pm) — $1,285pp ✓'},
    {id:'cl5',text:'DMK → CNX (Jun 5, morning) — $51pp ✓'},
    {id:'cl6',text:'CNX → HAN (Jun 8, morning) — $225pp ✓'},
    {id:'cl7',text:'Ha Giang Loop tour — $400pp ✓'},
    {id:'cl8',text:'Bangkok Airbnb — Jun 1–5 — $105pp ✓'},
    {id:'cl9',text:'Mad Monkey Chiang Mai — Jun 5–8 — $41.28pp ✓'},
  ]},
  {title:'Book Hostels',items:[
    {id:'cl10',text:'Lub d Phuket Patong — 5 nights Jun 15–20 — ~$90pp — Hostelworld'},
    {id:'cl11',text:'The Farm Hostel Canggu, Bali — 5 nights Jun 20–25 — ~$65pp — Hostelworld'},
    {id:'cl12',text:'Airport guesthouse near Noi Bai Hanoi — Jun 14 (arrive 2am) — ~$15pp'},
  ]},
  {title:'Health & Medical',items:[
    {id:'cl13',text:'Schedule GP / travel medicine appointment (4+ weeks before May 30)'},
    {id:'cl14',text:'Get Hepatitis A vaccine'},
    {id:'cl15',text:'Get Typhoid vaccine'},
    {id:'cl16',text:'Get malaria prescription (Malarone or Doxycycline)'},
    {id:'cl17',text:'Ask GP about Rabies vaccine for Bali'},
    {id:'cl18',text:'Ask GP about Japanese Encephalitis (Ha Giang rural Vietnam)'},
    {id:'cl19',text:'Stock up on regular medications — 60-day supply'},
    {id:'cl20',text:'Pack first aid kit: Imodium, Pepto, ibuprofen, antihistamine, antiseptic wipes, blister pads, rehydration sachets'},
  ]},
  {title:'Documents',items:[
    {id:'cl21',text:'Verify passports valid 6+ months past Jun 25 (must not expire before Dec 25, 2025)'},
    {id:'cl22',text:'Make 2 physical copies of each passport'},
    {id:'cl23',text:'Email yourself all booking confirmations'},
    {id:'cl24',text:'Note Bali Visa on Arrival: $35 USD cash at DPS airport'},
    {id:'cl25',text:'Register with US STEP program at step.state.gov (free)'},
    {id:'cl26',text:'Save US Embassy Bangkok (+66 2 205 4000) + Hanoi (+84 24 3850 5000) as contacts'},
    {id:'cl27',text:'Send parents: itinerary + hostel addresses + Ha Giang tour contact + SafetyWing policy number'},
  ]},
  {title:'Money & Banking',items:[
    {id:'cl28',text:'Notify both banks/cards: Thailand, Vietnam, Indonesia — May 30–Jun 25'},
    {id:'cl29',text:'Apply for Charles Schwab debit card (reimburses all global ATM fees)'},
    {id:'cl30',text:'Set up Wise or Revolut as backup'},
    {id:'cl31',text:'Have $35 USD cash separately ready for Bali Visa on Arrival'},
  ]},
  {title:'Apps — Download on Home WiFi',items:[
    {id:'cl32',text:'Grab (Thailand + Vietnam)'},
    {id:'cl33',text:'GoJek (Indonesia / Bali)'},
    {id:'cl34',text:'Google Maps — download offline: Bangkok, Chiang Mai, Hanoi, Ha Giang, Phuket, Canggu'},
    {id:'cl35',text:'Google Translate — download offline: Thai, Vietnamese, Indonesian'},
    {id:'cl36',text:'WhatsApp'},
    {id:'cl37',text:'XE Currency'},
    {id:'cl38',text:'Hostelworld'},
  ]},
  {title:'Final Week',items:[
    {id:'cl39',text:'Buy SafetyWing travel insurance at safetywing.com (~$104pp for 26 nights)'},
    {id:'cl40',text:'Thailand SIM or eSIM (AIS or DTAC — can buy at BKK airport on arrival)'},
    {id:'cl41',text:'Confirm all offline Google Maps downloaded'},
    {id:'cl42',text:'Online check-in for DFW→BKK (opens 24hrs before May 30 10:55pm)'},
    {id:'cl43',text:'Confirm both banks are in travel mode'},
    {id:'cl44',text:'Pack bag — lay everything out, then put a third of it back'},
    {id:'cl45',text:'Charge everything: phone, power bank, camera, earbuds'},
    {id:'cl46',text:'Send parents the final itinerary'},
    {id:'cl47',text:'Confirm DFW parking or drop-off — arrive airport by 8:30pm May 30'},
  ]},
];

const PACKING_GROUPS = [
  {title:'Documents & Money',items:[
    {id:'pk1',text:'Passport (valid 6+ months past Jun 25)'},
    {id:'pk2',text:'2 physical copies of passport'},
    {id:'pk3',text:'$35 USD cash for Bali Visa on Arrival — SEPARATE envelope'},
    {id:'pk4',text:'Credit/debit cards (travel-notified)'},
    {id:'pk5',text:'Charles Schwab debit card'},
    {id:'pk6',text:'SafetyWing policy number / travel insurance card'},
  ]},
  {title:'Clothing — Quick-Dry Only, No Cotton',items:[
    {id:'pk7',text:'5 quick-dry t-shirts'},
    {id:'pk8',text:'2 shorts'},
    {id:'pk9',text:'1 lightweight long pants (temples + Ha Giang)'},
    {id:'pk10',text:'Flip flops'},
    {id:'pk11',text:'1 pair closed shoes (Ha Giang + Mount Batur 2am trek)'},
    {id:'pk12',text:'Underwear + socks (6–7 pairs)'},
    {id:'pk13',text:'Lightweight packable rain jacket'},
    {id:'pk14',text:'Swimwear × 2'},
  ]},
  {title:'Gear — Non-Negotiable',items:[
    {id:'pk15',text:'Dry bag 10L minimum — ESSENTIAL for Phi Phi + Gili T + boat days'},
    {id:'pk16',text:'Portable power bank 20,000mAh — carry-on only, NOT checked baggage'},
    {id:'pk17',text:'Headlamp — Ha Giang homestays + Mount Batur 2am departure'},
    {id:'pk18',text:'Combination padlock for hostel lockers'},
    {id:'pk19',text:'Universal travel adapter (Thailand Type A/B, Indonesia Type C/F)'},
    {id:'pk20',text:'Waterproof phone pouch — boat days and swimming'},
    {id:'pk21',text:'Anti-theft travel wallet (under clothing — RFID blocking)'},
    {id:'pk22',text:'Microfiber towel'},
    {id:'pk23',text:'Earplugs — Phuket + Bali party hostels'},
  ]},
  {title:'Health & Hygiene',items:[
    {id:'pk24',text:'Reef-safe sunscreen × 2 bottles — required at Bali marine sites'},
    {id:'pk25',text:'Mosquito repellent 30%+ DEET (Vietnam especially)'},
    {id:'pk26',text:'Malaria prescription (Malarone or Doxycycline)'},
    {id:'pk27',text:'First aid kit: Imodium, Pepto, ibuprofen, antihistamine, antiseptic wipes, blister pads, rehydration sachets'},
    {id:'pk28',text:'Any regular medications — full trip supply'},
    {id:'pk29',text:'Hand sanitizer'},
    {id:'pk30',text:'Toiletries (travel sizes)'},
  ]},
  {title:'Electronics',items:[
    {id:'pk31',text:'Phone + charger cable'},
    {id:'pk32',text:'Earbuds / headphones'},
    {id:'pk33',text:'Camera (optional)'},
  ]},
];
